### ISSUE TITLE
IllegalAccessError

### ISSUE THREAD

**Issue by rtorrisi** [coffee4j/coffee4j-example#1]
Actually, I'm not able to use coffee4j or test your example as I always got this error:

```
java.lang.IllegalAccessError: tried to access method de.rwth.swc.coffee4j.model.manager.CombinatorialTestConsumerManagerConfiguration.<init>(Lde/rwth/swc/coffee4j/model/manager/CombinatorialTestConsumerManagerConfiguration$Builder;)V from class de.rwth.swc.coffee4j.model.manager.CombinatorialTestConsumerManagerConfiguration$Builder
```

**Comment by kfoegen** [comment]
Can you give me some information on your setup, e.g. which OS, Java version and how did you start the test?

**Comment by rtorrisi** [comment]
Thank you for your reply!

OS: Deepin 15.9
Java version: Java openjdk 11
IDE: IDEA IntelliJ

I cloned the repo and imported in IntelliJ with Maven using the pom.xml file.
So I imported dependencies, then I tried to execute all tests with no success as that error occurrs.

**Comment by ghost** [comment]
Have you tried executing the test via the Maven command line (i.e. `mvn clean test`) instead of using Intellij?

**Comment by rtorrisi** [comment]
> Have you tried executing the test via the Maven command line (i.e. `mvn clean test`) instead of using Intellij?

Yes, I tried it too but nothing changed.

Anyway, I extracted .java files sources from the *-1.0.1-sources.jar files and I compiled on my own with success and all worked fine. So we should investigate what's wrong with the libraries.
